regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 1
    keep_embeddings_frozen: True
    optimizer: Adam
    encoder_learning_rate: 1.0e-05
    learning_rate: 3.0e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    pool: avg
    layer: mix
    dropout: 0.1
    batch_size: 2
    train_data: # PATH TO CSV FILE WITH ORIGINAL AND ADDED SYNTHETIC DIRECT ASSESSMENT DATA FROM 2017 TO 2019
    validation_data: # PATH TO DEV FILE
    hidden_sizes:
      - 3072
      - 1536
    load_weights_from_checkpoint: null

trainer: trainer_da.yaml
early_stopping: early_stopping.yaml
model_checkpoint: model_checkpoint_da.yaml
